---
apiVersion: v1
data:
  app.py: |
    from flask import Flask
    import urllib.parse
    
    app = Flask(__name__)

    @app.route('{{.Values.app.route }}')
    
    def hello_world():
       text = "<a href={}>This is a link to the Github repo with Dockerfile and chart</a>".format("https://{{.Values.app.link }}")
       return(text)
        
       

    if __name__ == "__main__":
        app.run(debug=True, host='0.0.0.0')
kind: ConfigMap
metadata:
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:app.py: {}
    manager: kubectl
  name: sample-app-configmap
