apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-hello-world.fullname" . }}
  labels:
    {{- include "k8s-hello-world.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
      protocol: TCP
      name: https
  selector:
    {{- include "k8s-hello-world.selectorLabels" . | nindent 4 }}
